channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cython
  - ipython
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  # - scikit-image
  # - scikit-learn
  # - sympy
  # - colorcet
  # - scipy
  # - notebook
  # - bokeh>=2.1
  # - selenium
  # - datashader
  # - flask
  # - firefox
  # - geckodriver
  # - holoviews
  # - hvplot
  - jupyter_contrib_nbextensions
